image: publysher/hugo

pages:
  script:
    - mkdir themes
    - cd themes
    - git clone https://github.com/dplesca/purehugo.git
    - cd ../
    - hugo -v
  artifacts:
    paths:
    - public
  only:
  - master

